version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    working_dir: /app/online-ide
    command: ["quasar", "dev", "-p", "8080"]

  code-server:
    image: codercom/code-server:latest
    volumes:
      - .:/home/coder/project
      - /app/node_modules
    ports:
      - "8081:8081" # Expose code-server on port 8081
    environment:
      - PASSWORD=your-password-here # Set a password for access or use --auth none to disable authentication
      - GIT_USER=your-name
      - GIT_EMAIL=your-email@example.com
    command: ["--auth", "none", "--bind-addr", "0.0.0.0:8081", "--disable-telemetry"]