version: '3.8'

services:
  app:
    image: node:latest
    container_name: quasar-dev-container
    tmpfs:
      - /app/.local/share/code-server
    volumes:
      - ./online-ide:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: /bin/sh -c "npm install -g @quasar/cli && npm install && quasar dev -p 8080"

  pyhton-playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "8888:8888"
    volumes:
      - ./data:/home/developer
    environment:
      CODE_SERVER_TELEMETRY_ENABLED: "false"
    command: ["/usr/local/bin/startup-script.sh"]
    